line-length = 150
indent-width = 4


[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = [
    "F",  # Pyflakes
    "E4",
    "E7",
    "E9",
    "E112",   # no-indented-block
    "E113",   # unexpected-indentation
    "I001",
    "I002"
]
ignore = []


[format]
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, use double quotes for strings.
quote-style = "double"

exclude = [
    ".git/",
    ".venv",
    "tmp/",
]
